// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NKC_Resource_Allocation;

#nullable disable

namespace NKC_Resource_Allocation.Migrations
{
    [DbContext(typeof(NKC_DbContext))]
    partial class NKC_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NKC_Resource_Allocation.DbModels.Auditors", b =>
                {
                    b.Property<string>("AuditorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuditorNRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NKCAuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditorId");

                    b.ToTable("Auditors");
                });

            modelBuilder.Entity("NKC_Resource_Allocation.DbModels.Documents", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuditorNRCBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorNRCFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarrelAndCO2_Res_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarrelAndCO2_Res_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarrelAndCO2_Res_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarrelAndCO2_Res_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarrelAndCO2_Res_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarrelAndCO2_Res_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarrelAndCO2_Res_7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarrelAndCO2_Res_8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine_Res_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine_Res_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine_Res_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine_Res_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine_Res_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutletId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("AuditorId");

                    b.HasIndex("OutletId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("NKC_Resource_Allocation.DbModels.Outlets", b =>
                {
                    b.Property<string>("OutletId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutletCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutletSerialNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutletId");

                    b.ToTable("Outlets");
                });

            modelBuilder.Entity("NKC_Resource_Allocation.DbModels.Documents", b =>
                {
                    b.HasOne("NKC_Resource_Allocation.DbModels.Auditors", "Auditors")
                        .WithMany()
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NKC_Resource_Allocation.DbModels.Outlets", "Outlets")
                        .WithMany()
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditors");

                    b.Navigation("Outlets");
                });
#pragma warning restore 612, 618
        }
    }
}
